version: '3'

services:
  redis:
    image: tempworks/redis-server:3.2.100-windowsservercore-1809
    networks:
      - default
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  srps:
    image: tempworks/sovren-srps:latest-1809
    networks:
      - default

  convert:
    image: tempworks/convert-service:latest-1809
    networks:
      - default

  login:
    image: tempworks/login-server:$LOGIN_VERSION
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_CONFIG_BASEPATH=c:\app\config
      - SERILOG_DEBUG=true
    volumes:
      - c:/ProgramData/TempWorks/config/login-server:c:/app/config
      - c:/ProgramData/TempWorks/logs/login-server:c:/app/logs
    networks:
      - default
    restart: always
    expose:
      - "80"
    ports:
      - "55180:80"
    depends_on:
      - redis

  api-server:
    image: tempworks/api3-server:$API3_VERSION
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_CONFIG_BASEPATH=c:\app\config
      - SERILOG_DEBUG=true
    volumes:
      - c:/ProgramData/TempWorks/config/api-server:c:/app/config
      - c:/ProgramData/TempWorks/logs/api-server:c:/app/logs
    networks:
      - default
    restart: always
    expose:
      - "80"
    ports:
      - "55080:80"
    depends_on:
      - login
      - redis
      - srps
      - convert

networks:
  default:
    external:
      name: nat
